### ISSUE TITLE
Using wmata?

### ISSUE THREAD

**Issue by emma-k-alexandra** [joedborg/libwmata#1]
Hi there,

Was wondering if there are any ways my crate, [wmata](https://crates.io/crates/wmata), can support your needs. If there's anything I can add that would encourage you to use my crate, I'd love to hear it.

**Comment by joedborg** [comment]
Hey @emma-k-alexandra,

Honestly, I was just building a project for a display at home so we can see when the next train leaving the close by station is, and my Google fu let me down so I started writing one.  I can see yours is far more feature complete, so I’ll take a look at using it :)

**Comment by joedborg** [comment]
@emma-k-alexandra Also, feel free to raise a PR against the README pointing to WMATA.  Something like “You probably want the more feature rich...”.  I’m on plane WLAN at the moment and it’ll take half an hour to push the change 😂
